version: '3.9'

services:
  db:
    image: postgres:15
    container_name: pmv_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_vault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: pmv_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  api:
    build:
      context: ../../apps/api
    container_name: pmv_api
    depends_on:
      - db
      - minio
    ports:
      - "4000:4000"
    env_file:
      - ../../apps/api/.env

  web:
    build:
      context: ../../apps/web
    container_name: pmv_web
    depends_on:
      - api
    ports:
      - "3000:3000"
    env_file:
      - ../../apps/web/.env

volumes:
  postgres_data:
  minio_data:
